import Link from "next/link";
import { notFound } from "next/navigation";
import { OutgoingInvoiceLinesEditor } from "@/components/OutgoingInvoiceLinesEditor";
import { itemPriceTypes } from "@/lib/inventory";
import { outgoingInvoiceStatusLabel } from "@/lib/outgoing-invoice";
import { prisma } from "@/lib/prisma";
import { readWorkContext } from "@/lib/work-context";
import { getInventoryContext, InventoryAccessDenied, MissingInventoryContext } from "../../_shared";
import { finalizeOutgoingInvoice, fiscalizeOutgoingInvoice, saveOutgoingInvoiceDraft, updateOutgoingInvoiceHeader } from "../actions";

const messages: Record<string, string> = { kreirana: "Nacrt je otvoren. Dodajte stavke računa.", sacuvana: "Stavke i obračun fakture su sačuvani.", zaglavlje: "Podaci računa su sačuvani.", stavke: "Dodajte najmanje jednu stavku.", artikal: "Izabrani artikal nije dostupan.", pdv: "Artikal mora imati podešenu PDV stopu.", iznosi: "Provjerite količine, cijene i rabate.", nije_nacrt: "Mijenjati se može samo nacrt fakture.", magacin: "Izabrani magacin nije dostupan.", magacin_obavezan: "Za fakturu koja sadrži robu izaberite magacin.", pdv_period: "PDV period za datum računa je zaključan.", podesavanja: "Prvo podesite sva potrebna konta u Robno → Podešavanja.", vrsta_naloga: "Nije dostupna vrsta naloga Izlazni računi.", konto: "Konto iz šeme nije dostupan.", balans: "Šema fakture nije izbalansirana.", fiskalizacija_obavezna: "Ova firma koristi Summa fiskalizaciju. Faktura se ne može završiti bez uspješne fiskalizacije." };
function money(value: { toString(): string }) { return Number(value.toString()).toLocaleString("de-DE", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
export default async function OutgoingInvoiceDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ poruka?: string }> }) {
  const [{ id }, { poruka }, context, work] = await Promise.all([params, searchParams, getInventoryContext("view"), readWorkContext()]);
  if (!context.firma || !work.poslovnaGodinaId) return <MissingInventoryContext title="Izlazna faktura" />;
  if (!context.allowed) return <InventoryAccessDenied title="Izlazna faktura" />;
  const [invoice, items, warehouses, groups, units, vatRates] = await Promise.all([
    prisma.fiskalniIzlazniRacun.findFirst({ where: { id, agencija_id: context.user.agencija_id!, firma_id: context.firma.id, poslovna_godina_id: work.poslovnaGodinaId, is_deleted: false }, include: { kupac: true, magacin: true, firma: { select: { fiscalCompanyLink: { select: { fiscal_environment: true } } } }, poslovna_godina: { select: { zakljucena: true } }, stavke: { orderBy: { redni_broj: "asc" } } } }),
    prisma.artikal.findMany({ where: { agencija_id: context.user.agencija_id!, firma_id: context.firma.id, aktivan: true, is_deleted: false }, include: { jedinica_mjere: true, pdv_stopa: true, cijene: { where: { aktivna: true, is_deleted: false, OR: [{ vazi_od: null }, { vazi_od: { lte: new Date() } }], AND: [{ OR: [{ vazi_do: null }, { vazi_do: { gte: new Date() } }] }] }, orderBy: [{ created_at: "desc" }] } }, orderBy: [{ sifra: "asc" }, { naziv: "asc" }] }),
    prisma.magacin.findMany({ where: { agencija_id: context.user.agencija_id!, firma_id: context.firma.id, aktivan: true, is_deleted: false }, orderBy: [{ sifra: "asc" }] }),
    prisma.grupaArtikla.findMany({ where: { agencija_id: context.user.agencija_id!, firma_id: context.firma.id, aktivna: true, is_deleted: false }, orderBy: { naziv: "asc" }, select: { id: true, sifra: true, naziv: true } }),
    prisma.jedinicaMjere.findMany({ where: { aktivna: true }, orderBy: [{ redosljed: "asc" }, { naziv: "asc" }], select: { id: true, sifra: true, naziv: true } }),
    prisma.pdvStopa.findMany({ where: { agencija_id: context.user.agencija_id!, aktivna: true }, orderBy: [{ redosljed: "asc" }, { procenat: "asc" }], select: { id: true, naziv: true, procenat: true } })
  ]);
  if (!invoice) notFound();
  const fiscalizedDraft = invoice.status === "DRAFT" && invoice.fiscal_status === "Fiscalized";
  const editable = invoice.status === "DRAFT" && !invoice.poslovna_godina.zakljucena && !fiscalizedDraft;
  const fiscalizationPending = invoice.fiscal_status === "FiscalizationPending" && Boolean(invoice.last_fiscal_attempt_at && Date.now() - invoice.last_fiscal_attempt_at.getTime() < 2 * 60 * 1000);
  const options = items.filter((item) => item.pdv_stopa).map((item) => {
    const prices = item.cijene; const chosen = prices.find((price) => price.komitent_id === invoice.kupac_id && (!price.magacin_id || price.magacin_id === invoice.magacin_id)) ?? prices.find((price) => price.magacin_id === invoice.magacin_id) ?? prices.find((price) => price.tip === itemPriceTypes.promotional) ?? prices.find((price) => price.tip === itemPriceTypes.retail) ?? prices.find((price) => price.tip === itemPriceTypes.wholesale) ?? prices[0];
    return { id: item.id, code: item.sifra, name: item.naziv, unit: item.jedinica_mjere.oznaka, vat: context.firma!.pdv_obveznik ? Number(item.pdv_stopa!.procenat.toString()) : 0, service: item.usluga, netPrice: chosen?.cijena_bez_pdv.toString() ?? "", grossPrice: chosen?.cijena_sa_pdv.toString() ?? "" };
  });
  return <div className="admin-stack outgoing-invoice-page"><header className="admin-header"><div><p className="eyebrow">Robno / Prodaja / Izlazne fakture</p><h2>{invoice.interni_broj}</h2><p className="muted-text">{invoice.kupac.naziv} · {invoice.datum_racuna.toLocaleDateString("sr-Latn-ME")}</p></div><div className="header-actions"><span className="status-pill">{outgoingInvoiceStatusLabel(invoice.status)}</span><Link className="secondary-button" href={`/stampa/robno/izlazne-fakture/${invoice.id}`} target="_blank">Štampa</Link><Link className="secondary-button" href="/agencija/robno/izlazne-fakture">Nazad</Link></div></header>
    {poruka ? <p className="admin-message">{poruka.startsWith("zavrsena:") ? `Faktura je završena, lager je razdužen i kreiran je nalog ${poruka.split(":")[1] ?? ""}. Čeka preuzimanje u KIF.` : poruka.startsWith("lager:") ? `Nema dovoljno robe ${poruka.split(":")[1] ?? ""}. Dostupno: ${poruka.split(":")[2] ?? "0"}.` : poruka.startsWith("nabavna:") ? `Artikal ${poruka.split(":")[1] ?? ""} nema prosječnu nabavnu cijenu.` : poruka === "fiskalizacija_greska" ? `Fiscalizacija nije uspjela: ${invoice.fiscal_error_message ?? "Fiscal API je odbio zahtjev."}${invoice.correlation_id ? ` (Correlation ID: ${invoice.correlation_id})` : ""}` : poruka === "fiskalizacija_u_toku" ? "Fiskalizacija ovog računa je već pokrenuta. Sačekajte odgovor prije novog pokušaja." : messages[poruka] ?? poruka}</p> : null}
    <section className="metric-grid"><article className="metric"><span>Osnovica</span><strong>{money(invoice.ukupno_osnovica)} €</strong></article><article className="metric"><span>PDV</span><strong>{money(invoice.ukupno_izlazni_pdv)} €</strong></article><article className="metric"><span>Za plaćanje</span><strong>{money(invoice.ukupno_sa_pdv)} €</strong></article></section>
    <section className="admin-panel"><div className="panel-header"><div><h3>Podaci računa</h3><p className="muted-text">Kupac: {invoice.kupac.naziv}{invoice.kupac.pib ? ` · PIB ${invoice.kupac.pib}` : ""}</p></div><span>{invoice.fiskalizacija_rezim === "SUMMA" ? "Obavezna fiskalizacija kroz Summa" : "Bez fiskalizacije kroz Summa"}</span></div>{editable ? <form action={updateOutgoingInvoiceHeader} className="admin-form"><input type="hidden" name="firma_id" value={context.firma.id} /><input type="hidden" name="faktura_id" value={invoice.id} /><label><span>Magacin za robu</span><select name="magacin_id" defaultValue={invoice.magacin_id ?? (warehouses.length === 1 ? warehouses[0].id : "")}><option value="">Bez magacina (samo usluge)</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.sifra} · {warehouse.naziv}</option>)}</select></label><label><span>Način plaćanja</span><select name="nacin_placanja" defaultValue={invoice.nacin_placanja}><option value="BANK_TRANSFER">Virman</option><option value="CASH">Gotovina</option><option value="CARD">Kartica</option><option value="OTHER">Drugo</option></select></label><label className="form-wide"><span>Napomena</span><input name="napomena" defaultValue={invoice.napomena ?? ""} /></label><div className="form-actions form-wide"><button className="secondary-button" type="submit">Sačuvaj podatke računa</button></div></form> : <div className="invoice-summary-grid"><span>Datum prometa <strong>{invoice.datum_prometa.toLocaleDateString("sr-Latn-ME")}</strong></span><span>Datum valute <strong>{invoice.datum_valute?.toLocaleDateString("sr-Latn-ME") ?? "-"}</strong></span><span>Magacin <strong>{invoice.magacin ? `${invoice.magacin.sifra} · ${invoice.magacin.naziv}` : "-"}</strong></span></div>}</section>
    <section className="admin-form-section"><div className="panel-header"><div><h3>Stavke fakture</h3><p className="muted-text">Izaberite artikal, unesite količinu i po potrebi korigujte cijenu ili rabat.</p></div><span>{options.length} aktivnih artikala i usluga</span></div><form action={saveOutgoingInvoiceDraft}><input type="hidden" name="firma_id" value={context.firma.id} /><input type="hidden" name="faktura_id" value={invoice.id} /><OutgoingInvoiceLinesEditor disabled={!editable} items={options} groups={groups.map((group) => ({ id: group.id, label: `${group.sifra} · ${group.naziv}` }))} units={units.map((unit) => ({ id: unit.id, label: `${unit.sifra} · ${unit.naziv}` }))} vatRates={vatRates.map((rate) => ({ id: rate.id, label: `${rate.naziv} (${rate.procenat.toString()}%)` }))} initialLines={invoice.stavke.map((line) => ({ itemId: line.artikal_id, quantity: line.kolicina.toString(), netUnitPrice: line.jedinicna_cijena_bez_pdv.toString(), discountPercent: line.rabat_procenat.toString(), note: line.napomena ?? "" }))} />{editable ? <div className="form-actions"><button className="primary-button" type="submit">Sačuvaj nacrt</button></div> : null}</form></section>
    {editable || fiscalizedDraft ? <section className="admin-panel"><div className="panel-header"><div><h3>Završavanje fakture</h3><p className="muted-text">{fiscalizedDraft ? "Račun je fiskalizovan. Završite knjiženje i slanje u red za KIF." : "Poslije uspješne fiskalizacije sistem kreira nalog i postavlja fakturu da čeka KIF."}</p></div><span>{invoice.fiskalizacija_rezim === "SUMMA" ? `Fiskalno okruženje: ${invoice.firma.fiscalCompanyLink?.fiscal_environment ?? "provjera pri slanju"}` : "Bez Summa fiskalizacije"}</span></div><form action={fiscalizedDraft ? finalizeOutgoingInvoice : invoice.fiskalizacija_rezim === "SUMMA" ? fiscalizeOutgoingInvoice : finalizeOutgoingInvoice} className="form-actions"><input type="hidden" name="firma_id" value={context.firma.id} /><input type="hidden" name="faktura_id" value={invoice.id} /><button className="primary-button" disabled={!invoice.stavke.length || fiscalizationPending} type="submit">{fiscalizedDraft ? "Završi knjiženje" : invoice.fiskalizacija_rezim === "SUMMA" ? fiscalizationPending ? "Fiskalizacija u toku…" : "Fiskalizuj" : "Završi fakturu i kreiraj nalog"}</button></form>{invoice.fiskalizacija_rezim === "SUMMA" && !fiscalizedDraft ? <p className="admin-hint">Dugme automatski koristi aktivno Test ili Production okruženje. U produkciji ovaj klik predstavlja eksplicitnu potvrdu slanja konačnog nacrta.</p> : null}</section> : null}
  </div>;
}
