import Link from "next/link";
import { getPosContext } from "@/lib/pos";
import { prisma } from "@/lib/prisma";
import { configureDefaultPosRegister, registerInitialCashDeposit, updatePosAccountingIntegration } from "./actions";

export default async function PosSettingsPage({ searchParams }: { searchParams: Promise<{ poruka?: string; kod?: string }> }) {
  const [{ poruka, kod }, ctx] = await Promise.all([searchParams, getPosContext("manage")]);
  if (!ctx.firma || !ctx.allowed) return <section className="admin-panel"><p>Nemate pravo upravljanja POS podešavanjima.</p></section>;
  const [settings, registers] = await Promise.all([
    prisma.posPodesavanje.findUnique({ where: { firma_id: ctx.firma.id } }),
    prisma.posRegister.findMany({ where: { firma_id: ctx.firma.id, is_deleted: false }, orderBy: { naziv: "asc" } })
  ]);
  return <div className="admin-stack"><header className="admin-header"><div><p className="eyebrow">POS / Podešavanja</p><h2>Povezivanje kase</h2><p className="muted-text">Kasa koristi aktivnu poslovnu jedinicu, ENU i operatora iz Fiscal API-ja.</p></div><Link className="secondary-button" href="/agencija/pos">Otvori POS</Link></header>
    {poruka ? <p className={`status-banner ${["sacuvano", "depozit_sacuvan", "integracija_sacuvana"].includes(poruka) ? "success" : "error"}`}>{poruka === "sacuvano" ? "Kasa je povezana i POS je aktiviran." : poruka === "integracija_sacuvana" ? "Računovodstvena integracija je sačuvana. Postojeći POS računi su razvrstani prema načinu plaćanja." : poruka === "depozit_sacuvan" ? "Početni gotovinski depozit je uspješno prijavljen Poreskoj upravi." : poruka === "depozit_iznos" ? "Unesite ispravan iznos depozita (nula ili pozitivan iznos, najviše dvije decimale)." : poruka === "depozit_production" ? "Produkcijska prijava depozita nije dostupna kroz postojeću Fiscal API rutu. Testni endpoint se neće koristiti za produkciju." : poruka === "depozit_greska" ? `Prijava depozita nije uspjela${kod ? ` (${kod})` : ""}.` : poruka === "api" ? `Fiscal API trenutno nije dostupan${kod ? ` (${kod})` : ""}. Pokrenite API i pokušajte ponovo.` : "POS nije moguće aktivirati. Provjerite fiskalni readiness firme."}</p> : null}
    <section className="admin-panel"><div className="panel-header"><h3>Aktivacija</h3><span>{settings?.aktivan ? "POS aktivan" : "POS nije aktivan"}</span></div><p>Automatsko povezivanje bira prvi aktivni objekat, pripadajući ENU i aktivnog operatora iz istog Test ili Production okruženja.</p><form action={configureDefaultPosRegister}><button className="primary-button" type="submit">Poveži / osvježi KASU-1</button></form></section>
    <section className="admin-panel"><div className="panel-header"><h3>Računovodstvena integracija</h3><span>{settings?.racunovodstvena_integracija ? "Uključena" : "Isključena"}</span></div><p className="muted-text">Kada je uključena, fiskalizovani virmani se pojedinačno pripremaju za KIF po šemi izlaznih računa. Gotovina i kartica čekaju zbirni dnevni ili mjesečni pazar.</p><form action={updatePosAccountingIntegration} className="form-grid"><label><input name="accounting_integration" type="checkbox" defaultChecked={settings?.racunovodstvena_integracija ?? false}/> Uključi povezivanje POS-a sa KIF-om i glavnom knjigom</label><button className="primary-button" type="submit">Sačuvaj integraciju</button></form></section>
    <section className="admin-panel"><div className="panel-header"><h3>Kase i početni depozit</h3><span>{registers.length} ukupno</span></div><p className="muted-text">Prije prvog gotovinskog računa prijavite iznos novca koji se nalazi u kasi. Ako kasa počinje prazna, unesite 0,00.</p>{registers.map((register) => <div className="settings-card" key={register.id}><strong>{register.naziv}</strong><p className="muted-text">{register.sifra} · {register.fiscal_business_unit_name ?? "Objekat"} · ENU {register.fiscal_device_code ?? register.fiscal_device_id}</p>{register.cash_deposit_registered_at ? <p className="status-banner success">Prijavljeno {Number(register.cash_deposit_amount ?? 0).toFixed(2)} € · {register.cash_deposit_environment} · {register.cash_deposit_registered_at.toLocaleString("sr-Latn-ME")}{register.cash_deposit_fcdc ? ` · FCDC ${register.cash_deposit_fcdc}` : ""}</p> : <p className="status-banner error">Početni depozit još nije prijavljen.</p>}<form action={registerInitialCashDeposit} className="form-grid"><input type="hidden" name="register_id" value={register.id}/><label>Iznos početnog depozita (€)<input name="cash_amount" inputMode="decimal" defaultValue={register.cash_deposit_amount?.toString() ?? "0,00"} required /></label><button className="primary-button" type="submit">Prijavi početni depozit</button></form></div>)}</section>
  </div>;
}
